language: android
dist: precise
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
android:
  components:
    - tools
    - platform-tools
    - tools # not a mistakenly duplicated line: used above api 25.x
    - build-tools-29.0.1
    - android-29
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
  - yes | sdkmanager "platforms;android-29"
install: true
script:
  - ./gradlew apptentive-core:test -q
  - ./gradlew apptentive-feedback:test -q
  - ./gradlew apptentive-enjoyment-dialog:test -q
  - ./gradlew apptentive-survey:test -q
  - ./gradlew apptentive-notes:test -q