apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:stable
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  - name: compose
    image: "docker/compose:1.24.1"
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  - name: aws-cli
    image: "mesosphere/aws-cli"
    command: ['cat']
    tty: true
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
